name: MineMail
main: com.alta189.minemail.MineMail
version: 1.3
authors: [PhysX, alta189]
commands:
  mail:
    description: Some description here
    usage:
  mm:
    description: Some description here
    usage: